 mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root


mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['/home/senz/bankz/mongodb:/data/db']
    ports:
        - 27017:27017


switch:
    image: erangaeb/senzswitch:0.52
    container_name: senzswitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=172.17.0.1
        - SWITCH_MODE=DEV
    volumes:
        ['/home/senz/bankz/switch/logs:/app/logs', '/home/senz/bankz/switch/keys:/app/.keys']
    links:
        - mongodb


trans:
    image: erangaeb/sdbltrans:0.6
    container_name: trans
    environment:
        - SWITCH_HOST=172.17.0.1
        - SWITCH_PORT=7070
        - MYSQL_HOST=172.17.0.1
        - MYSQL_PORT=3306
        - EPIC_HOST=124.43.16.185
        - EPIC_PORT=8200
    volumes:
        ['/home/senz/bankz/trans/logs:/app/logs:rw', '/home/senz/bankz/trans/keys:/app/.keys:rw']
    links:
        - mysql
        - switch
