mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        ['$MYSQL_DATA_DIR:/var/lib/mysql']


mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['$MONGO_DATA_DIR:/data/db']
    ports:
        - 27017:27017


switch:
    image: erangaeb/senzswitch:0.57
    container_name: senzswitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$SWITCH_LOGS_DIR:/app/logs:rw', '$SWITCH_KEYS_DIR:/app/.keys:rw']
    links:
        - mongodb


web:
    image: hpcal1/sdblweb:0.11
    container_name: web
    ports:
        - 3000:3000
    environment:
        - APP_DB_HOST=${APP_DB_HOST}
        - APP_DB_DATABASE=${APP_DB_DATABASE}
        - RAILS_ENV=${RAILS_ENV}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
        ['$WEB_LOGS_DIR:/myapp/logs:rw']
    links:
        - mysql


trans:
    image: erangaeb/sdbltrans:1.5
    container_name: trans
    environment:
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
        - DB_NAME=${DB_NAME}
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_PORT=${MYSQL_PORT}
        - EPIC_HOST=${EPIC_HOST}
        - EPIC_PORT=${EPIC_PORT}
    volumes:
        ['$TRANS_LOGS_DIR:/app/logs:rw', '$TRANS_KEYS_DIR:/app/.keys:rw']
    links:
        - switch
        - mysql
        - web


inq:
    image: erangaeb/sdblinq:1.3
    container_name: inq
    environment:
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
        - EPIC_HOST=${EPIC_HOST}
        - EPIC_PORT=${EPIC_PORT}
    volumes:
        ['$INQ_LOGS_DIR:/app/logs:rw', '$INQ_KEYS_DIR:/app/.keys:rw']
    links:
        - switch


nginx:
    image: erangaeb/senznginx:0.4
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    links:
        - web


dashboard:
    image: hpcal1/senziesdashboard:0.3
    container_name: dashboard
    ports:
        - 4000:4000
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - MONGO_DB=${MONGO_DB}
    links:
        - mongodb
