mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root


mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['/home/senz/bankz/mongodb:/data/db']
    ports:
        - 27017:27017


switch:
    image: erangaeb/senzswitch:0.53
    container_name: senzswitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=172.17.0.1
        - SWITCH_MODE=PROD
    volumes:
        ['/home/senz/bankz/switch/logs:/app/logs', '/home/senz/bankz/switch/keys:/app/.keys']
    links:
        - mongodb

          
web:
    image: hpcal1/sdblweb:0.7
    container_name: web
    ports:
        - 3000:3000
    environment:
        - APP_DB_HOST=172.17.0.1
        - APP_DB_DATABASE=sdbl
        - RAILS_ENV=production
        - SECRET_KEY_BASE=6534ecca28d582de97251ca2e7a0a3b43a7aed9e0a4be5006ba4088757c72830602053fe047f2e8f30d828ff10def3ba8c9bcc0063e87521a8bc7f300f5a3cdc
    volumes:
        ['/home/senz/bankz/web/logs:/myapp/logs:rw']
    links:
        - mysql


trans:
    image: erangaeb/sdbltrans:1.2
    container_name: trans
    environment:
        - SWITCH_HOST=172.17.0.1
        - SWITCH_PORT=7070
        - DB_NAME=sdbl
        - MYSQL_HOST=172.17.0.1
        - MYSQL_PORT=3306
        - EPIC_HOST=10.100.31.240 
        - EPIC_PORT=8200
    volumes:
        ['/home/senz/bankz/trans/logs:/app/logs:rw', '/home/senz/bankz/trans/keys:/app/.keys:rw']
    links:
        - switch
        - web

inq:
    image: erangaeb/sdblinq:1.0
    container_name: inq
    environment:
        - SWITCH_HOST=172.17.0.1
        - SWITCH_PORT=7070
        - EPIC_HOST=10.100.31.240
        - EPIC_PORT=8200
    volumes:
        ['/home/senz/bankz/inq/logs:/app/logs:rw', '/home/senz/bankz/inq/keys:/app/.keys:rw']
    links:
        - switch
